# This is a basic workflow to help you get started with Actions
name: Refresh team board

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  refresh:
    name: Refresh team board
    runs-on: ubuntu-latest
    steps:
      - run: wget ${{ secrets.TEAM_URL }}